### PR TITLE
Update sections

### PR DESCRIPTION
**Pull request by JohnTitor**
Replace dummy sections.
I add two sections, features and example. The content is from README.

<details>
<summary>screenshots</summary>

### PC

image

### mobile

image

### PC

image

### mobile

image

</details>

### CODE REVIEW

**Comment by JohnTitor** [comment]
@vertexclique It changes many contents, could you review it?
preview page: https://deploy-preview-4--mystifying-turing-4adf24.netlify.com/

**Comment by vertexclique** [comment]
Looks good, one suggestion might be adding `fort` declaration as get started. So people also understand that they don't mightn't need that piece of code.

**Review by vertexclique — APPROVED** [review]
i can give only `fort` remark. Like:

In a short way, you can use `fort` the proc-macro of bastion.
```rust
#[fort::root]
fn main() {
    println!("Running in Bastion runtime!");
}
```

or you can configure every piece by yourself:

_long example here_

Don't mind my wording. Maybe the wording can be better between the lines.

**Comment by JohnTitor** [comment]
Add `fort` example

**Comment by vertexclique** [comment]
Noice! :shipit:

**Pull request merged**
